/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package junior.football.league;
import java.io.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *Runs the Match GUI
 * @author Eldram
 */
public class matchUI extends javax.swing.JFrame {

    /**
     * Creates new form matchUI
     * @param JLMatch a new instance of Match that allows the access to programming in the Match class.
     */
    Matches JLMatch;

    /**
     *sets all of the dropdowns using the relevant text methods.
     */
    public matchUI() {
        initComponents();
        JLMatch = new Matches();
        homeTeam.setModel(new DefaultComboBoxModel<>(Teams.textTeams()));
        awayTeam.setModel(new DefaultComboBoxModel<>(Teams.textTeams()));
        refSelect.setModel(new DefaultComboBoxModel<>(Referee.textRefs()));
        hPlayer1.setModel(new DefaultComboBoxModel<>(Players.textPlayers()));
        hPlayer2.setModel(new DefaultComboBoxModel<>(Players.textPlayers()));
        hPlayer3.setModel(new DefaultComboBoxModel<>(Players.textPlayers()));
        hPlayer4.setModel(new DefaultComboBoxModel<>(Players.textPlayers()));
        hPlayer5.setModel(new DefaultComboBoxModel<>(Players.textPlayers()));
        hPlayer6.setModel(new DefaultComboBoxModel<>(Players.textPlayers()));
        hPlayer7.setModel(new DefaultComboBoxModel<>(Players.textPlayers()));
        hPlayer8.setModel(new DefaultComboBoxModel<>(Players.textPlayers()));
        hPlayer9.setModel(new DefaultComboBoxModel<>(Players.textPlayers()));
        hPlayer10.setModel(new DefaultComboBoxModel<>(Players.textPlayers()));
        hPlayer11.setModel(new DefaultComboBoxModel<>(Players.textPlayers()));
        hPlayer12.setModel(new DefaultComboBoxModel<>(Players.textPlayers()));
        hPlayer13.setModel(new DefaultComboBoxModel<>(Players.textPlayers()));
        aPlayer1.setModel(new DefaultComboBoxModel<>(Players.textPlayers()));
        aPlayer2.setModel(new DefaultComboBoxModel<>(Players.textPlayers()));
        aPlayer3.setModel(new DefaultComboBoxModel<>(Players.textPlayers()));
        aPlayer4.setModel(new DefaultComboBoxModel<>(Players.textPlayers()));
        aPlayer5.setModel(new DefaultComboBoxModel<>(Players.textPlayers()));
        aPlayer6.setModel(new DefaultComboBoxModel<>(Players.textPlayers()));
        aPlayer7.setModel(new DefaultComboBoxModel<>(Players.textPlayers()));
        aPlayer8.setModel(new DefaultComboBoxModel<>(Players.textPlayers()));
        aPlayer9.setModel(new DefaultComboBoxModel<>(Players.textPlayers()));
        aPlayer10.setModel(new DefaultComboBoxModel<>(Players.textPlayers()));
        aPlayer11.setModel(new DefaultComboBoxModel<>(Players.textPlayers()));
        aPlayer12.setModel(new DefaultComboBoxModel<>(Players.textPlayers()));
        aPlayer13.setModel(new DefaultComboBoxModel<>(Players.textPlayers()));
        hCaptain.setModel(new DefaultComboBoxModel<>(Players.textPlayers()));
        aCaptain.setModel(new DefaultComboBoxModel<>(Players.textPlayers()));
        hStaff1.setModel(new DefaultComboBoxModel<>(ClubStaff.textCS()));
        hStaff2.setModel(new DefaultComboBoxModel<>(ClubStaff.textCS()));
        aStaff1.setModel(new DefaultComboBoxModel<>(ClubStaff.textCS()));
        aStaff2.setModel(new DefaultComboBoxModel<>(ClubStaff.textCS()));
        deleteMatchSelect.setModel(new DefaultComboBoxModel<> (JLMatch.textMatch()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        homeTeam = new javax.swing.JComboBox<>();
        awayTeam = new javax.swing.JComboBox<>();
        header1 = new javax.swing.JLabel();
        header2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        subtitle1 = new javax.swing.JLabel();
        subtitle4 = new javax.swing.JLabel();
        hPlayer1 = new javax.swing.JComboBox<>();
        hPlayer2 = new javax.swing.JComboBox<>();
        hPlayer3 = new javax.swing.JComboBox<>();
        hPlayer4 = new javax.swing.JComboBox<>();
        hPlayer5 = new javax.swing.JComboBox<>();
        hPlayer6 = new javax.swing.JComboBox<>();
        hPlayer7 = new javax.swing.JComboBox<>();
        hPlayer8 = new javax.swing.JComboBox<>();
        hPlayer9 = new javax.swing.JComboBox<>();
        hPlayer10 = new javax.swing.JComboBox<>();
        hPlayer11 = new javax.swing.JComboBox<>();
        aPlayer1 = new javax.swing.JComboBox<>();
        aPlayer2 = new javax.swing.JComboBox<>();
        aPlayer3 = new javax.swing.JComboBox<>();
        aPlayer4 = new javax.swing.JComboBox<>();
        aPlayer5 = new javax.swing.JComboBox<>();
        aPlayer6 = new javax.swing.JComboBox<>();
        aPlayer7 = new javax.swing.JComboBox<>();
        aPlayer8 = new javax.swing.JComboBox<>();
        aPlayer9 = new javax.swing.JComboBox<>();
        aPlayer10 = new javax.swing.JComboBox<>();
        aPlayer11 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        hPlayer12 = new javax.swing.JComboBox<>();
        hPlayer13 = new javax.swing.JComboBox<>();
        aPlayer12 = new javax.swing.JComboBox<>();
        aPlayer13 = new javax.swing.JComboBox<>();
        subtitle5 = new javax.swing.JLabel();
        refSelect = new javax.swing.JComboBox<>();
        subtitle2 = new javax.swing.JLabel();
        subtitle3 = new javax.swing.JLabel();
        hStaff1 = new javax.swing.JComboBox<>();
        aStaff1 = new javax.swing.JComboBox<>();
        hStaff2 = new javax.swing.JComboBox<>();
        aStaff2 = new javax.swing.JComboBox<>();
        submitMatchButton = new javax.swing.JButton();
        subtitle6 = new javax.swing.JLabel();
        deleteMatchSelect = new javax.swing.JComboBox<>();
        deleteMatchButton = new javax.swing.JButton();
        returnButton = new javax.swing.JButton();
        reuturnButton = new javax.swing.JButton();
        hCaptain = new javax.swing.JComboBox<>();
        aCaptain = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        printMatchButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        title.setText("Match Creation");

        homeTeam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        awayTeam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        header1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        header1.setText("Home Team");

        header2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        header2.setText("Away Team");

        jLabel4.setText("vs");

        subtitle1.setText("Home Players");

        subtitle4.setText("Away Players");

        hPlayer1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        hPlayer2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        hPlayer3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        hPlayer4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        hPlayer5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        hPlayer6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        hPlayer7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        hPlayer8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        hPlayer9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        hPlayer10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        hPlayer11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        aPlayer1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        aPlayer1.setMaximumSize(new java.awt.Dimension(56, 20));

        aPlayer2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        aPlayer3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        aPlayer4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        aPlayer5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        aPlayer6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        aPlayer7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        aPlayer8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        aPlayer9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        aPlayer10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        aPlayer11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Home Substitutes");

        jLabel8.setText("Away Substitutes");

        hPlayer12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        hPlayer13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        aPlayer12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        aPlayer13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        subtitle5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        subtitle5.setText("Referee");

        refSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        subtitle2.setText("Home Manager and Coach");

        subtitle3.setText("Away Manager and Coach");

        hStaff1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        aStaff1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        hStaff2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        aStaff2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        submitMatchButton.setText("SUBMIT MATCH");
        submitMatchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMatchButtonMouseClicked(evt);
            }
        });

        subtitle6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        subtitle6.setText("Delete Match");

        deleteMatchSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        deleteMatchButton.setText("Delete Match");
        deleteMatchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMatchButtonMouseClicked(evt);
            }
        });

        returnButton.setText("Return to Main");
        returnButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnButtonMouseClicked(evt);
            }
        });

        reuturnButton.setText("Return");
        reuturnButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reuturnButtonMouseClicked(evt);
            }
        });
        reuturnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reuturnButtonActionPerformed(evt);
            }
        });

        hCaptain.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        aCaptain.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        aCaptain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aCaptainActionPerformed(evt);
            }
        });

        jLabel1.setText("Captain");

        jLabel2.setText("Captain");

        printMatchButton1.setText("Print Match Reports");
        printMatchButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printMatchButton1MouseClicked(evt);
            }
        });
        printMatchButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printMatchButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(header1)
                        .addGap(453, 453, 453)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 479, Short.MAX_VALUE)
                        .addComponent(header2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(hPlayer12, javax.swing.GroupLayout.Alignment.LEADING, 0, 250, Short.MAX_VALUE)
                                .addComponent(hPlayer11, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hPlayer10, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hPlayer9, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hPlayer8, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hPlayer7, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hPlayer6, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hPlayer5, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hPlayer4, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hPlayer3, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hPlayer2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hPlayer1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hPlayer13, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel7)
                            .addComponent(subtitle1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(hStaff2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(subtitle2)
                                                        .addGap(54, 54, 54))
                                                    .addComponent(hStaff1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(hCaptain, 0, 180, Short.MAX_VALUE)
                                                .addGap(203, 203, 203))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(returnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(50, 50, 50)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(aCaptain, 0, 180, Short.MAX_VALUE)
                                            .addComponent(subtitle3, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(aStaff1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(aStaff2, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(59, 59, 59)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(subtitle5)
                                            .addGap(262, 262, 262))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(deleteMatchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(reuturnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(217, 217, 217))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(deleteMatchSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(83, 83, 83)
                                                    .addComponent(subtitle6))
                                                .addComponent(submitMatchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(64, 64, 64)
                                            .addComponent(refSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(167, 167, 167)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(printMatchButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(214, 214, 214)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(aPlayer12, 0, 250, Short.MAX_VALUE)
                            .addComponent(aPlayer11, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(aPlayer9, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(aPlayer8, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(aPlayer7, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(aPlayer6, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(aPlayer5, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(aPlayer4, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(aPlayer10, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(aPlayer13, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(subtitle4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(aPlayer1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(aPlayer2, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(aPlayer3, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(homeTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(awayTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(485, 485, 485)
                .addComponent(title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(title)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(header1)
                    .addComponent(header2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(homeTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(awayTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(subtitle1)
                                    .addComponent(subtitle4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(aPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(aPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(hPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hPlayer3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aPlayer3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hPlayer4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aPlayer4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aCaptain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(subtitle2)
                                    .addComponent(subtitle3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(hStaff1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(aStaff1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hStaff2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(aStaff2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hCaptain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hPlayer5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aPlayer5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hPlayer6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aPlayer6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hPlayer7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aPlayer7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hPlayer8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aPlayer8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hPlayer9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aPlayer9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hPlayer10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aPlayer10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hPlayer11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aPlayer11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hPlayer12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aPlayer12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hPlayer13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aPlayer13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(subtitle5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(submitMatchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(subtitle6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteMatchSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteMatchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(printMatchButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(reuturnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(448, 448, 448)
                        .addComponent(returnButton)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnButtonMouseClicked
                this.setVisible(false); //makes the Match GUI not visable when pressed.
                new jflUI().setVisible(true); //makes the Home GUI visable.
    }//GEN-LAST:event_returnButtonMouseClicked

    private void reuturnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reuturnButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reuturnButtonActionPerformed

    private void aCaptainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aCaptainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aCaptainActionPerformed

    private void printMatchButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printMatchButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printMatchButton1ActionPerformed

    private void reuturnButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reuturnButtonMouseClicked
                this.setVisible(false);
                new jflUI().setVisible(true);
    }//GEN-LAST:event_reuturnButtonMouseClicked

    private void submitMatchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMatchButtonMouseClicked
        
        JLMatch.ref = "Referee: " + refSelect.getSelectedItem().toString();
        JLMatch.match = "Home Team: " + homeTeam.getSelectedItem().toString() + " vs Away Team: " + awayTeam.getSelectedItem().toString();
        JLMatch.homeStaff = "Home Staff: " +  hStaff1.getSelectedItem().toString() + " and " + hStaff2.getSelectedItem().toString();
        JLMatch.homeCap = "Home Captain: " + hCaptain.getSelectedItem().toString();
        JLMatch.homeTeam = "Home Players: " + hPlayer1.getSelectedItem().toString() + ", " + hPlayer2.getSelectedItem().toString() + ", " + hPlayer3.getSelectedItem().toString() + ", " + hPlayer4.getSelectedItem().toString() + ", " + hPlayer5.getSelectedItem().toString() + ", " + hPlayer6.getSelectedItem().toString() + ", " + hPlayer7.getSelectedItem().toString() + ", " + hPlayer8.getSelectedItem().toString() + ", " + hPlayer9.getSelectedItem().toString() + ", " + hPlayer10.getSelectedItem().toString() + ", " + hPlayer11.getSelectedItem().toString();
        JLMatch.homeSubs = "Home Substitutes: " + hPlayer12.getSelectedItem().toString() + ", " + hPlayer13.getSelectedItem().toString();
        JLMatch.awayStaff = "Away Staff: " +  aStaff1.getSelectedItem().toString() + " and " + aStaff2.getSelectedItem().toString();
        JLMatch.awayCap = "Away Captain: " + aCaptain.getSelectedItem().toString();
        JLMatch.awayTeam = "Away Players: " + aPlayer1.getSelectedItem().toString() + ", " + aPlayer2.getSelectedItem().toString() + ", " + aPlayer3.getSelectedItem().toString() + ", " + aPlayer4.getSelectedItem().toString() + ", " + aPlayer5.getSelectedItem().toString() + ", " + aPlayer6.getSelectedItem().toString() + ", " + aPlayer7.getSelectedItem().toString() + ", " + aPlayer8.getSelectedItem().toString() + ", " + aPlayer9.getSelectedItem().toString() + ", " + aPlayer10.getSelectedItem().toString() + ", " + aPlayer11.getSelectedItem().toString();
        JLMatch.awaySubs = "Away Substitutes: " + aPlayer12.getSelectedItem().toString() + ", " + aPlayer13.getSelectedItem().toString();
        //declares all variables and what they contain.
        
        if(homeTeam.getSelectedItem() == awayTeam.getSelectedItem()){
            JOptionPane.showMessageDialog(new javax.swing.JPanel(), "Teams cannot be the same!");
            //if the two selected items are the same a JPanel will appear saying that the teams cannot be the same.            
        }else{
            JLMatch.createMatchReport(JLMatch.match, JLMatch.ref, JLMatch.homeStaff, JLMatch.homeCap, JLMatch.homeTeam, JLMatch.homeSubs, JLMatch.awayStaff, JLMatch.awayCap, JLMatch.awayTeam, JLMatch.awaySubs);
            JLMatch.createMatch(JLMatch.match);
           //if the is statement is not met then the createNatch() and createMatchReport() methods are both run with all attributes being inputted.            
        }
        
    }//GEN-LAST:event_submitMatchButtonMouseClicked

    private void printMatchButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMatchButton1MouseClicked

        System.out.println(JLMatch.matchReportArray);
        //if the print button is pushed all match reports are printed to the console.
    }//GEN-LAST:event_printMatchButton1MouseClicked

    private void deleteMatchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMatchButtonMouseClicked
        JLMatch.deleteMatch(deleteMatchSelect.getSelectedIndex());
        //when the button is pressed it runs the deleteMatch() method.
    }//GEN-LAST:event_deleteMatchButtonMouseClicked

    /**
     * runs the matchUI.
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(matchUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(matchUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(matchUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(matchUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new matchUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> aCaptain;
    private javax.swing.JComboBox<String> aPlayer1;
    private javax.swing.JComboBox<String> aPlayer10;
    private javax.swing.JComboBox<String> aPlayer11;
    private javax.swing.JComboBox<String> aPlayer12;
    private javax.swing.JComboBox<String> aPlayer13;
    private javax.swing.JComboBox<String> aPlayer2;
    private javax.swing.JComboBox<String> aPlayer3;
    private javax.swing.JComboBox<String> aPlayer4;
    private javax.swing.JComboBox<String> aPlayer5;
    private javax.swing.JComboBox<String> aPlayer6;
    private javax.swing.JComboBox<String> aPlayer7;
    private javax.swing.JComboBox<String> aPlayer8;
    private javax.swing.JComboBox<String> aPlayer9;
    private javax.swing.JComboBox<String> aStaff1;
    private javax.swing.JComboBox<String> aStaff2;
    private javax.swing.JComboBox<String> awayTeam;
    private javax.swing.JButton deleteMatchButton;
    private javax.swing.JComboBox<String> deleteMatchSelect;
    private javax.swing.JComboBox<String> hCaptain;
    private javax.swing.JComboBox<String> hPlayer1;
    private javax.swing.JComboBox<String> hPlayer10;
    private javax.swing.JComboBox<String> hPlayer11;
    private javax.swing.JComboBox<String> hPlayer12;
    private javax.swing.JComboBox<String> hPlayer13;
    private javax.swing.JComboBox<String> hPlayer2;
    private javax.swing.JComboBox<String> hPlayer3;
    private javax.swing.JComboBox<String> hPlayer4;
    private javax.swing.JComboBox<String> hPlayer5;
    private javax.swing.JComboBox<String> hPlayer6;
    private javax.swing.JComboBox<String> hPlayer7;
    private javax.swing.JComboBox<String> hPlayer8;
    private javax.swing.JComboBox<String> hPlayer9;
    private javax.swing.JComboBox<String> hStaff1;
    private javax.swing.JComboBox<String> hStaff2;
    private javax.swing.JLabel header1;
    private javax.swing.JLabel header2;
    private javax.swing.JComboBox<String> homeTeam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton printMatchButton1;
    private javax.swing.JComboBox<String> refSelect;
    private javax.swing.JButton returnButton;
    private javax.swing.JButton reuturnButton;
    private javax.swing.JButton submitMatchButton;
    private javax.swing.JLabel subtitle1;
    private javax.swing.JLabel subtitle2;
    private javax.swing.JLabel subtitle3;
    private javax.swing.JLabel subtitle4;
    private javax.swing.JLabel subtitle5;
    private javax.swing.JLabel subtitle6;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
