/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package junior.football.league;
import java.io.*;
import java.util.Scanner;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *Runs the Players GUI
 * @author Eldram
 */
public class playersUI extends javax.swing.JFrame {
 Players JLPlayers;
    
    
    
   /**
     * Creates new form playersUI
     * @param JLPlayers new instance of Players
     * sets Model for team dropdown using textTeams().
     * sets Model for the player dropdown using textTeams().
     */
    public playersUI() {
        initComponents(); //runs the method to create teh GUI.
        JLPlayers = new Players();
        teamDropD.setModel(new DefaultComboBoxModel<>(Teams.textTeams()));
        playerSelectDD.setModel(new DefaultComboBoxModel<> (JLPlayers.textPlayers()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        subtitle1 = new javax.swing.JLabel();
        playerNameField = new javax.swing.JTextField();
        ageField = new javax.swing.JTextField();
        positionDropD = new javax.swing.JComboBox<>();
        teamDropD = new javax.swing.JComboBox<>();
        subtitle2 = new javax.swing.JLabel();
        addPlayerButton = new javax.swing.JButton();
        playerSelectDD = new javax.swing.JComboBox<>();
        deletePlayerButton = new javax.swing.JButton();
        returnButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        title.setText("Player Editor");

        subtitle1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        subtitle1.setText("Add a Player");

        playerNameField.setText("Player Name...");

        ageField.setText("Player Age...");

        positionDropD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Goalkeeper", "Defender", "Midfielder", "Forward" }));
        positionDropD.setToolTipText("");

        teamDropD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamDropDActionPerformed(evt);
            }
        });

        subtitle2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        subtitle2.setText("Delete a Player");

        addPlayerButton.setText("Add Player");
        addPlayerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addPlayerButtonMouseClicked(evt);
            }
        });

        playerSelectDD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        deletePlayerButton.setText("Delete Player");
        deletePlayerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletePlayerButtonMouseClicked(evt);
            }
        });

        returnButton.setText("Return to Main");
        returnButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(156, 156, 156))
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(subtitle1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(addPlayerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(playerSelectDD, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(subtitle2))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(playerNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                .addComponent(positionDropD, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ageField)
                                .addComponent(teamDropD, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(deletePlayerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(returnButton, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(subtitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(positionDropD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teamDropD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addPlayerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(subtitle2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerSelectDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deletePlayerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(returnButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnButtonMouseClicked
                this.setVisible(false); //makes the Players GUI not visable when pressed.
                new jflUI().setVisible(true); //makes the Home GUI visable.
    }//GEN-LAST:event_returnButtonMouseClicked

    private void addPlayerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addPlayerButtonMouseClicked
        
        if(playerNameField.getText().isEmpty() && ageField.getText().isEmpty()){
            JOptionPane.showMessageDialog(new javax.swing.JPanel(), "Please Fill all Sections.");
            //if the textfields for name and age are empty the error panel telling the user to fill all sections.
        }else{
           JLPlayers.createPlayer(playerNameField.getText(), positionDropD.getSelectedItem().toString(), ageField.getText(), teamDropD.getSelectedItem().toString()); 
           //if the is statement is not met then the createPlayer() method is run with all attributes being inputted.
        }

    }//GEN-LAST:event_addPlayerButtonMouseClicked


    
    private void teamDropDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamDropDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teamDropDActionPerformed

    private void deletePlayerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletePlayerButtonMouseClicked
        JLPlayers.deletePlayer(playerSelectDD.getSelectedIndex());
        //when the button is pressed it runs the deletePlayers() method.
    }//GEN-LAST:event_deletePlayerButtonMouseClicked

    /**
     * runs the playersUI.
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(playersUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(playersUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(playersUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(playersUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new playersUI().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPlayerButton;
    private javax.swing.JTextField ageField;
    private javax.swing.JButton deletePlayerButton;
    private javax.swing.JTextField playerNameField;
    private javax.swing.JComboBox<String> playerSelectDD;
    private javax.swing.JComboBox<String> positionDropD;
    private javax.swing.JButton returnButton;
    private javax.swing.JLabel subtitle1;
    private javax.swing.JLabel subtitle2;
    private javax.swing.JComboBox<String> teamDropD;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
