/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package junior.football.league;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *Runs the results GUI.
 * @author Eldram
 */
public class resultUI extends javax.swing.JFrame {

    /**
     *creates public int dH and sets it to 0.
     */
    public int dH = 0;

    /**
     *creates public int dA and sets it to 0.
     */
    public int dA = 0;

    /**
     *creates public int wH and sets it to 0.
     */
    public int wH = 0;

    /**
     *creates public int lH and sets it to 0.
     */
    public int lA = 0;
    /**
     * Creates new form resultUI
     * @param JLOutcome new instance of Results.
     * sets both the home and away dropdowns using textTeams().
     */
    MatchOutcome JLOutcome;
    public resultUI() {
        initComponents(); //runs the method to create the GUI.
        JLOutcome = new MatchOutcome();
        hTeam.setModel(new DefaultComboBoxModel<>(Teams.textTeams()));
        aTeam.setModel(new DefaultComboBoxModel<>(Teams.textTeams()));

    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        hTeam = new javax.swing.JComboBox<>();
        subtitle1 = new javax.swing.JLabel();
        subtitle2 = new javax.swing.JLabel();
        subtitle3 = new javax.swing.JLabel();
        submitResultButton = new javax.swing.JButton();
        returnButton = new javax.swing.JButton();
        hScore = new javax.swing.JTextField();
        aScore = new javax.swing.JTextField();
        aTeam = new javax.swing.JComboBox<>();
        printResultsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        title.setText("Match Result");

        hTeam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        subtitle1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        subtitle1.setText("Select a Teams");

        subtitle2.setText("Home Score");

        subtitle3.setText("Away Score");

        submitResultButton.setText("SUBMIT RESULT");
        submitResultButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitResultButtonMouseClicked(evt);
            }
        });

        returnButton.setText("Return to Main");
        returnButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnButtonMouseClicked(evt);
            }
        });

        aScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aScoreActionPerformed(evt);
            }
        });

        aTeam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        printResultsButton.setText("Print Results");
        printResultsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printResultsButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(title)
                            .addComponent(subtitle1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(hTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(aTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(subtitle2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(hScore))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(subtitle3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(aScore))))))
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(submitResultButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(returnButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(printResultsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(subtitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(aTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subtitle2)
                    .addComponent(subtitle3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(submitResultButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(printResultsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(returnButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnButtonMouseClicked
                this.setVisible(false); //makes the Results GUI not visable when pressed.
                new jflUI().setVisible(true); //makes the Home GUI visable.
    }//GEN-LAST:event_returnButtonMouseClicked

    private void aScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aScoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aScoreActionPerformed

    private void submitResultButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitResultButtonMouseClicked

        if(hTeam.getSelectedItem() == aTeam.getSelectedItem()){
            JOptionPane.showMessageDialog(new javax.swing.JPanel(), "Please Select Different Teams.");
            //if the two teams selected are the same then there will be a error message presented telling the user to select a different team.
        }else{
           JLOutcome.createResults(hTeam.getSelectedItem().toString(), aTeam.getSelectedItem().toString(), hScore.getText(), aScore.getText());
           //if the is statement is not met then the createResults() method is run with all attributes being inputted.           
        }
        
        
        int homeScore = 0;
        int awayScore = 0;
        //sets homeScore and awayScore to 0.
        
        try {
            homeScore = Integer.parseInt(hScore.getText());
            awayScore = Integer.parseInt(aScore.getText());
            //changes the text from the textfields to an integer and sets the got ints to homeScore and awayScore.
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(new javax.swing.JPanel(), "Error, Can't find file!");
            //if the file can't be found the catch exception will be caught and produces a Jpanel with a Error message.
        }
        
        if(homeScore == awayScore) {
            dH = hTeam.getSelectedIndex();
            dA = aTeam.getSelectedIndex();
            JLOutcome.draw(dH,dA);
            //if the scores are the same after being pulled, then the MatchOutcoome draw method is run.
                    
        } else if (homeScore > awayScore) {
            wH = hTeam.getSelectedIndex();
            JLOutcome.win(wH);
            //if the first statement ins't met and the home score is better than away score then the MatchOutcome win method is run.
        } else {
            lA = aTeam.getSelectedIndex();
            JLOutcome.lose(lA);
            //if both if statements are not met then the MatchOutcome lose method is run.
        }
    }//GEN-LAST:event_submitResultButtonMouseClicked

    private void printResultsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printResultsButtonMouseClicked
        System.out.println(JLOutcome.resultArray);
        //System.out.println(JLOutcome.textResults());
        //prints out the results array when the print button is clicked.
    }//GEN-LAST:event_printResultsButtonMouseClicked

    /**
     * runs the resultsUI.
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(resultUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(resultUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(resultUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(resultUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new resultUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aScore;
    private javax.swing.JComboBox<String> aTeam;
    private javax.swing.JTextField hScore;
    private javax.swing.JComboBox<String> hTeam;
    private javax.swing.JButton printResultsButton;
    private javax.swing.JButton returnButton;
    private javax.swing.JButton submitResultButton;
    private javax.swing.JLabel subtitle1;
    private javax.swing.JLabel subtitle2;
    private javax.swing.JLabel subtitle3;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
