/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package junior.football.league;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
/**
 * Runs the GUI for the Teams section and uses methods from Teams.
 * @author Eldram
 */
public class teamUI extends javax.swing.JFrame {
    /**
     * Creates new form teamUI
     * Creates a new Teams instance with the name JLTeams.
     */
    
    Teams JLTeams;
    
    /**
     * @param JLTeams a new instance of Teams that allows the access to programming in the Teams class.
     * setsModel for the team select dropdown and uses the textTeams() method to fill the dropdown.
     */
    public teamUI() {
       initComponents();//runs the method to create the GUI.
       JLTeams = new Teams();
       //System.out.println(Teams.textTeams().length);
       teamSelectDD.setModel(new DefaultComboBoxModel<>(JLTeams.textTeams()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        submitTeamButton = new javax.swing.JButton();
        teamNameInput = new javax.swing.JTextField();
        deleteTeamButton = new javax.swing.JButton();
        returnButton = new javax.swing.JButton();
        teamSelectDD = new javax.swing.JComboBox<>();
        subtitle2 = new javax.swing.JLabel();
        subtitle1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        title.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        title.setText("Team Editor");

        submitTeamButton.setText("Submit Team");
        submitTeamButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitTeamButtonMouseClicked(evt);
            }
        });

        teamNameInput.setText("Enter Team Name...");
        teamNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamNameInputActionPerformed(evt);
            }
        });

        deleteTeamButton.setText("Delete Team");
        deleteTeamButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteTeamButtonMouseClicked(evt);
            }
        });

        returnButton.setText("Return to Menu");
        returnButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnButtonMouseClicked(evt);
            }
        });

        subtitle2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        subtitle2.setText("Delete a Team");

        subtitle1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        subtitle1.setText("Create a Team");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(subtitle1)
                            .addComponent(title)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(submitTeamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(returnButton)))
                .addContainerGap(145, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteTeamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(teamSelectDD, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(teamNameInput, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                .addGap(118, 118, 118))
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(subtitle2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addGap(35, 35, 35)
                .addComponent(subtitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teamNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(submitTeamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(subtitle2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teamSelectDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteTeamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(returnButton)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnButtonMouseClicked
                this.setVisible(false); //makes the Teams GUI not visable.
                new jflUI().setVisible(true); //sets the main home window to be visable.
    }//GEN-LAST:event_returnButtonMouseClicked

    private void teamNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamNameInputActionPerformed
    }//GEN-LAST:event_teamNameInputActionPerformed

    private void submitTeamButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitTeamButtonMouseClicked
        
        if(teamNameInput.getText().isEmpty()) { 
            JOptionPane.showMessageDialog(new javax.swing.JPanel(), "Text box is Empty");
            //System.out.print(JLTeams.teamArray);
            //if the text field is empty the if statement will cause a JPanel to appear saying the box needs to be filled.
        }else{
            JLTeams.createTeam(teamNameInput.getText());
        }   //if the if statement is not met then it runs the createTeams method from the Teams class.
            
        
    }//GEN-LAST:event_submitTeamButtonMouseClicked

    private void deleteTeamButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteTeamButtonMouseClicked
        JLTeams.deleteTeam(teamSelectDD.getSelectedIndex());
        //when the button is pressed it runs the deleteTeam() method from the Teams class.
    }//GEN-LAST:event_deleteTeamButtonMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    }//GEN-LAST:event_formWindowOpened

    /**
     * runs the TeamUI
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teamUI().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteTeamButton;
    private javax.swing.JButton returnButton;
    private javax.swing.JButton submitTeamButton;
    private javax.swing.JLabel subtitle1;
    private javax.swing.JLabel subtitle2;
    private javax.swing.JTextField teamNameInput;
    public javax.swing.JComboBox<String> teamSelectDD;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
